version: "3.9"

services:
  frontend:
    image: nginx-frontend
    build:
      context: ./frontend
      args:
       - REACT_APP_SERVICES=/services/m
    volumes:
      - ./frontend:/app/frontend
    ports:
     - "80:80"
    networks:
     - frontend
     - backend

  backend:
    image: wsgi-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    networks:
      - backend

  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization SQL script
      - sqlserver_data:/var/opt/mssql  # Persistent volume for database files
    environment:
      - MYSQL_ROOT_PASSWORD=${SQLSERVER_SA_PASSWORD}  
      - MYSQL_DATABASE=${DB_NAME}                      
      - MYSQL_USER=${MYSQL_USER}                                
      - MYSQL_PASSWORD=${SQLSERVER_SA_PASSWORD}       
    ports:
      - "${DB_PORT}:${DB_PORT}"  # Map MySQL port to the host
    restart: "on-failure"

networks:
  frontend:
  backend:

volumes:
  sqlserver_data:
  backend:
  frontend: